var express = require('express');
var router = express.Router();
var multer  = require('multer');



var storage = multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, 'public/uploads/')
    },
    filename: function (req, file, cb) {
      cb(null, file.originalname)
    }
  })

var upload = multer({ storage: storage })


var travellerController  =   require('../controller/travellerController')



router.get('/viewall', travellerController.viewAlltraveller);

router.post('/addtraveller', travellerController.addtraveller);

router.get('/:phoneNumber', travellerController.viewtraveller);

router.put('/update/:phoneNumber', travellerController.updatetraveller);

router.delete('/delete', travellerController.deletetraveller);

router.post('/login', travellerController.login);


// router.post('/viewTravellerByName', travellerController. );



router.post('/upload',upload.single('fileData'), (req, res) => {
    // logger.info(req.file);//this will be automatically set by multer
    // logger.info(req.body);

    console.log(req.file)
    console.log(req.body)


    //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
//     fs.readFile(req.file.path,(err, contents)=> {
//      if (err) {
//      console.log('Error: ', err);
//         res.end("End")
//     }else{
//      console.log('File contents ',contents);
//     res.end("file saved")
//     }
//    });


   res.end("file saved")



  });







module.exports = router;
